### ISSUE TITLE
Reencoding: jpg and jpeg

### ISSUE THREAD

**Issue by TrixiEther** [TrixiEther/DashchanFork#117]
Dashchan can reencode images to jpeg format. Perhaps should give the user the opportunity to choose what the format will be when posting the file, jpg or jpeg

**Comment by N3-M3-S1S** [comment]
@TrixiEther JPG and JPEG is the same format just with different extension name.

**Comment by TrixiEther** [comment]
@N3-M3-S1S I know it. The question is whether the user should be able to choose how the extension will look after transcoding. jpeg or jpg

**Comment by N3-M3-S1S** [comment]
@TrixiEther I don't think the ability to choose is necessary, but we could change jpeg to jpg because the latter is a more popular extension name.
