### ISSUE TITLE
Full view in gallery mode

### ISSUE THREAD

**Issue by darlopvil** [TrixiEther/DashchanFork#122]
hello, hope your doing great 👍

I won`t call it a feature but a little improvement in the gallery mode. Once you access this convenient feature, it's not possible to view pics "clearly". I'm not asking for a fullscreen mode (honestly,  i like to see the upper bar in my mobile), but the ability to see an image without these 2 annoying black layers up and down. 

See pic below as an example:
![bc2dea71-c8b6-44fa-b54c-b85dcfac561c](https://github.com/TrixiEther/DashchanFork/assets/60988792/3cd419eb-dbdf-443e-88ff-f9c1fb17d6ea)

can it be done? will it be too difficult?

Thanks for reading. Have a great day 🌞

**Comment by TrixiEther** [comment]
@darlopvil hello. I checked this behavior. When you open an image in the gallery, the layers are indeed present, but it is enough to click on the image once, and the application goes into full screen mode. This is how you control the view mode

**Comment by darlopvil** [comment]
It was so easy i feel so dumb rn

Indeed i tried it. Hold tap for a few seconds, checked config, etc... It works now smoothly.

Sorry and thanks 😔🙏

**Comment by TrixiEther** [comment]
@darlopvil no problem! While working with Dashchan, I met a lot of things that I did not suspect during the years of use 😆
Btw, it looks like the issue can be closed...
