### ISSUE TITLE
Текст-пикер

### ISSUE THREAD

**Issue by drizzle-mizzle** [TrixiEther/DashchanFork#132]
Не уверен, настолько именно это баг дашчана (присутствует в оригинальном в том числе) или системы, но на Самсунговой OneUI 2.5 в приложении очень странно работает текст пикер. 
При двойном клике по тексту, то просто ничего не происходит, то всё-таки появляется возможность продолжить жест третьим инпутом, после клика удержав палец, и тогда появляется текст пикер. Но чаще просто ничего не работает.
Очевидно, что дело именно в системе, так как раньше пользовался мейзу на FlymeOS, и ни с чем подобным не сталкивался, и наверное трудно будет отловить такое, если у тебя самого нет самсунга на руках, но можешь всё же попробовать поискать возможную причину проблемы по возможности? 
В других приложениях такого нет. Стилусом текст тоже выбирается нормально, но не всегда есть возможность его достать...

**Comment by drizzle-mizzle** [comment]
Примерно вот так это выглядит.
По всем постам одинаково кликаю два раза, после чего в них выделяется часть текста, и либо тут же пропадает, либо выделение переходит на какое-то одно слово, и тогда это означает, что пикер ухватил что-то, и можно нажать ещё раз с удержанием, чтобы появились ползунки.
https://github.com/TrixiEther/DashchanFork/assets/55811932/e2de6f36-daf7-4e98-8b2a-27a58a4aa236

**Comment by TrixiEther** [comment]
@drizzle-mizzle А какая у вас версия сейчас стоит? Последний релиз 1.6.2.1 что-то чинил вроде бы проблемы с выделением текста на андроид 14...

**Comment by drizzle-mizzle** [comment]
@TrixiEther она и стоит.
Версия андроид десятая.

**Comment by TrixiEther** [comment]
@drizzle-mizzle эмуляторов этой системы я к сожалению не нашел совсем. Можно только потестить на 10 андроиде, но если не воспроизведется, то видимо особенность OneUI

**Comment by drizzle-mizzle** [comment]
Понял. Ну глянь там. Если найдёшь, то хорошо, если нет, то и ладно, переживу. Всё равно до конца года наверное поменяю телефон уже.
