### ISSUE TITLE
Пост не помечается как мой, если запостить что-то и обновить тред до того, как этот пост появится

### ISSUE THREAD

**Issue by notsyncing12309** [TrixiEther/DashchanFork#143]
Может непонятно описал, но вот как воспроизвести баг:
1. Простишь на дваче;
2. После отправки, пока пост не отобразился, обновляешь тред (скайпом снизу вверх, например);
3. Вуаля, пост не отображается как твой, на нем просто нет пометки "Мой пост", и ещё иногда у такого поста не отображаются вложения.
При этом, если запостить и подождать отображения поста, не обновляя тред, пост нормально помечается как мой.

**Comment by TrixiEther** [comment]
@notsyncing12309 часто такое бывает, старая проблема актуальная для двача, причем можно поймать даже в браузере. Я думаю просто по таймауту отваливается постинг
