### ISSUE TITLE
Show user posts and replies positions on the scrollbar

### ISSUE THREAD

**Issue by N3-M3-S1S** [TrixiEther/DashchanFork#59]
We can show user posts and replies (and may be some other types of posts e.g. doubles/triples/etc, posts with many replies) on the scrollbar (like in some code editors) for more convenient navigation in a thread.

**Comment by TrixiEther** [comment]
Duplicate of #52
Ok, I'll reassign the old task, when it's ready - we'll close two things at once

**Comment by TrixiEther** [comment]
@N3-M3-S1S or it's another feature, only with scrollbar?

**Comment by N3-M3-S1S** [comment]
@TrixiEther this is for the scrollbar only.
