### ISSUE TITLE
Make user posts/answers border and scrollbar feature with the ability to disable

### ISSUE THREAD

**Issue by TrixiEther** [TrixiEther/DashchanFork#94]
By popular demand from workers...

@N3-M3-S1S please assign yourself if you are going to work with this

**Comment by N3-M3-S1S** [comment]
@TrixiEther Scrollbar marks can be disabled in current version, but there is no option to disable specific marks. 
May be i should add the ability to choose what marks and borders to show? E.g. show border only for replies.

**Comment by TrixiEther** [comment]
> May be i should add the ability to choose what marks and borders to show?

@N3-M3-S1S looks a bit redundant to me...

**Comment by N3-M3-S1S** [comment]
@TrixiEther Ok, then i will only add an option to enable/disable posts borders.
